<a href="https://colab.research.google.com/github/CristinaMarsh/Learning_/blob/main/Daily%20Practice/Pytorch_code_collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

# operation

## torch.triu

https://pytorch.org/docs/stable/generated/torch.triu.html


torch.triu (input, diagonal $=0, *$, out=None) $\rightarrow$ Tensor

- input (Tensor) – the input tensor
- diagonal (int, optional) – the diagonal to consider
- out (Tensor, optional) – the output tensor
- 如果diagonal为空，输入矩阵保留主对角线与主对角线以上的元素；
- 如果diagonal为正数n，输入矩阵保留主对角线与主对角线以上除去n行的元素；
- 如果diagonal为负数-n，输入矩阵保留主对角线与主对角线以上与主对角线下方h行对角线的元素；


In [3]:
a = torch.randn(4,4)

dig_a0 = torch.triu(a, diagonal=0)
print(dig_a0)
dig_apos = torch.triu(a, diagonal=1)
print(dig_apos)
dig_aneg = torch.triu(a, diagonal=-1)
print(dig_aneg)

tensor([[ 0.0507, -1.1710, -0.2697,  0.0324],
        [ 0.0000,  0.3586, -0.8233, -0.0704],
        [ 0.0000,  0.0000, -1.0652,  0.4921],
        [ 0.0000,  0.0000,  0.0000, -1.6045]])
tensor([[ 0.0000, -1.1710, -0.2697,  0.0324],
        [ 0.0000,  0.0000, -0.8233, -0.0704],
        [ 0.0000,  0.0000,  0.0000,  0.4921],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])
tensor([[ 0.0507, -1.1710, -0.2697,  0.0324],
        [ 1.0722,  0.3586, -0.8233, -0.0704],
        [ 0.0000, -0.1811, -1.0652,  0.4921],
        [ 0.0000,  0.0000,  0.1005, -1.6045]])


# nn

## torch.conv1d

torch.nn.Conv1d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros', device=None, dtype=None)

Applies a 1D convolution over an input signal composed of several input planes.
In the simplest case, the output value of the layer with input size $\left(N, C_{\text {in }}, L\right)$ and output $\left(N, C_{\text {out }}, L_{\text {out }}\right)$ can be precisely described as:

Parameters
- in_channels (int) - Number of channels in the input image
- out_channels (int) - Number of channels produced by the convolution
- kernel_size (int or tuple) - Size of the convolving kernel
- stride (int or tuple, optional) - Stride of the convolution. Default: 1
- padding (int, tuple or str, optional) - Padding added to both sides of the input. Default: 0
- padding_mode (string, optional) - 'zeros', 'reflect', 'replicate' or 'circular'. Default:
'zeros'
- dilation (int or tuple, optional) - Spacing between kernel elements. Default: 1
- groups (int, optional) - Number of blocked connections from input channels to output channels.
Default: 1
- bias (bool, optional) - If True , adds a learnable bias to the output. Default: True

Shape:
- Input: $\left(N, C_{i n}, L_{i n}\right)$ or $\left(C_{i n}, L_{i n}\right)$
- Output: $\left(N, C_{\text {out }}, L_{\text {out }}\right)$ or $\left(C_{o u t}, L_{\text {out }}\right)$, where
$$
L_{o u t}=\left\lfloor\frac{L_{i n}+2 \times \text { padding }-\text { dilation } \times(\text { kernel_size }-1)-1}{\text { stride }}+1\right\rfloor
$$

In [4]:
def N_out_cal(L_in, padding, dilation, kernel_size, stride):
    
    Lout = (L_in + 2 * padding - dilation * (kernel_size - 1) -1) / stride + 1 
    return Lout

In [5]:
#In time series, pred, and Lout?
conv1 = nn.Conv1d(16, 1, 3, stride=2) # (Feature, outputchannel, kernel_size = 1)
input = torch.randn(20, 16, 50) #(B, Cin(Feature), Lin(T))
output = conv1(input) #output Tensor with shape torch.Size([20, 1, 24]) (B, ?, ?)

In [6]:
L_in, padding, dilation, kernel_size, stride = 50, 0, 1, 3, 2
N_out_cal(L_in, padding, dilation, kernel_size, stride)

24.5

# Tools

## Shape check

In [9]:
! pip install torchsummary

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [10]:
from torchvision import models
from torchsummary import summary

vgg = models.vgg16()
summary(vgg, (3, 224, 224))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 64, 224, 224]           1,792
              ReLU-2         [-1, 64, 224, 224]               0
            Conv2d-3         [-1, 64, 224, 224]          36,928
              ReLU-4         [-1, 64, 224, 224]               0
         MaxPool2d-5         [-1, 64, 112, 112]               0
            Conv2d-6        [-1, 128, 112, 112]          73,856
              ReLU-7        [-1, 128, 112, 112]               0
            Conv2d-8        [-1, 128, 112, 112]         147,584
              ReLU-9        [-1, 128, 112, 112]               0
        MaxPool2d-10          [-1, 128, 56, 56]               0
           Conv2d-11          [-1, 256, 56, 56]         295,168
             ReLU-12          [-1, 256, 56, 56]               0
           Conv2d-13          [-1, 256, 56, 56]         590,080
             ReLU-14          [-1, 256,